### ISSUE TITLE
Please tag a release

### ISSUE THREAD

**Issue by fd0** [inconshreveable/mousetrap#2]
For [restic](https://github.com/restic/restic), we've switch to `dep` recently, and it would be very helpful if you could tag a release, e.g. `v1.0.0`. Thanks!

https://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases

**Comment by inconshreveable** [comment]
sure thing! https://github.com/inconshreveable/mousetrap/releases/tag/v1.0

**Comment by fd0** [comment]
Cool, thanks!

**Comment by fd0** [comment]
I'm sorry to bother you again, but since I've opened the issue, the Go versioning proposal was accepted and it mandates that version tags must be of the form `vX.Y.Z` and conform to semantic versioning. So unfortunately the tag `v1.0` is not considered by it.

Would you mind adding a tag `v1.0.0` (pointing to the same commit as `v1.0`)? That'd be awesome!

**Comment by fd0** [comment]
Cool, thank you!
