### ISSUE TITLE
Update LICENSE text to reflect full apache license

### ISSUE THREAD

**Issue by caniszczyk** [inconshreveable/mousetrap#5]
https://github.com/inconshreveable/mousetrap/blob/master/LICENSE

At the moment, when you view the project from GitHub's UI, it doesn't auto detect the license as Apache v2.0

<img width="316" alt="Screen Shot 2022-08-03 at 7 20 49 PM" src="https://user-images.githubusercontent.com/63777/182728929-5d55c217-0044-447f-8207-9e0c20a67e90.png">

**Comment by inconshreveable** [comment]
fixed, thank you!
